### ISSUE TITLE
Bug: Substitution already present

### ISSUE THREAD

**Issue by paultristanwagner** [paultristanwagner/satisfiability-checking#1]
Certain queries to the simplex algorithm can cause an exception.

```
simplex x>=-1 y<=10 x+y=3 y>=1 max(2x+y)
```

```
Exception in thread "main" java.lang.IllegalArgumentException: value already present: subst0
                at com.google.common.collect.HashBiMap.put(HashBiMap.java:310)
                at com.google.common.collect.HashBiMap.put(HashBiMap.java:290)
                at me.paultristanwagner.satchecking.theory.Simplex2.transformOffsetVariables(Simplex2.java:350)
                at me.paultristanwagner.satchecking.theory.Simplex2.solve(Simplex2.java:133)
                at me.paultristanwagner.satchecking.CLI.main(CLI.java:127)
```

**Comment by paultristanwagner** [comment]
This seems to be caused by the method `freshVariable` since it does not know about the other substitutions.
